Update terraform-pull-request.yaml
Updated pull request github actions workflow

diff --git a/github_action_workflows/terraform-pull-request.yaml b/github_action_workflows/terraform-pull-request.yaml
--- a/github_action_workflows/terraform-pull-request.yaml
+++ b/github_action_workflows/terraform-pull-request.yaml
@@ -26,12 +26,16 @@ jobs:
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
           aws-region: us-east-1
 
       # Downloads a specific version of Terraform CLI and adds it to PATH
       # Marketplace: https://github.com/marketplace/actions/hashicorp-setup-terraform
       - name: Setup - Terraform CLI
         uses: hashicorp/setup-terraform@v1
+        with:
+          terraform_version: 1.0.8
 
       #https://github.com/marketplace/actions/setup-tflint
       - name: Setup TFLint
@@ -40,77 +44,37 @@ jobs:
           tflint_version: latest
           github_token: ${{ secrets.GITHUB_TOKEN }}
 
-      #https://github.com/dorny/paths-filter
-      - name: "Path Filter"
-        uses: dorny/paths-filter@v2.2.1
-        id: filter
-        with:
-          filters: |
-            dev:
-              - 'dev/**'
-            prod:
-              - 'prod/**'
-
       #----------------------------- Action -------------------------------#
-      # tflint Prod Folder
+      # tflint Folder
       - name: Run TFLint
-        if: steps.filter.outputs.prod == 'true'
-        run: cd prod && tflint -f compact
+        run: tflint -f compact
+        
+      # Terraform fmt
+      - name: Terraform Format prod
+        id: fmt
+        run: terraform fmt -check
 
-      # tflint Dev Folder
-      - name: Run TFLint
-        if: steps.filter.outputs.dev == 'true'
-        run: cd dev && tflint -f compact
-
-      # Terraform init prod
-      - name: Terraform Init Prod
-        id: init_prod
-        if: steps.filter.outputs.prod == 'true'
-        run: cd prod && terraform init -input=false
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_GHA_NAMEOFREPO_PROD }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_GHA_NAMEOFREPO_PROD }}
-        # GIT_SSH_COMMAND: "echo '${{ secrets.IHM_GH_SREBOT_SSH }}' > id_rsa
+      # Terraform init
+      - name: Terraform Init
+        id: init
+        run: terraform init -input=false
+        # GIT_SSH_COMMAND: "echo '${{ secrets.GH_SSH }}' > id_rsa
         # && ssh-keyscan github.com > known_hosts
         # && chmod 600 id_rsa known_hosts
         # && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
-
-      # Terraform init nonprod
-      - name: Terraform Init Dev
-        id: init_dev
-        if: steps.filter.outputs.dev == 'true'
-        run: cd dev && terraform init -input=false
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_GHA_NAMEOFREPO_NONPROD}}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_GHA_NAMEOFREPO_NONPROD }}
-        # GIT_SSH_COMMAND: "echo '${{ secrets.IHM_GH_SREBOT_SSH }}' > id_rsa
-        # && ssh-keyscan github.com > known_hosts
-        # && chmod 600 id_rsa known_hosts
-        # && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
-
+        
+      # Terraform validate
+      - name: Terraform Validate
+        id: validate
+        run: terraform validate -no-color
+        continue-on-error: true
+        
       # The id value is used for reference in the comment step via "steps.plan.outputs.stdout"
       # Note: Color is disabled to prevent messy characters from appearing in the pull request comment
-      - name: Terraform Plan Prod
-        id: plan_prod
-        if: github.event_name == 'pull_request' && steps.filter.outputs.prod == 'true'
-        run: cd prod && terraform plan -no-color
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_GHA_NAMEOFREPO_PROD }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_GHA_NAMEOFREPO_PROD }}
-        # GIT_SSH_COMMAND: "echo '${{ secrets.IHM_GH_SREBOT_SSH }}' > id_rsa
-        # && ssh-keyscan github.com > known_hosts
-        # && chmod 600 id_rsa known_hosts
-        # && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
-        continue-on-error: true
-
-      - name: Terraform Plan Dev
-        id: plan_dev
-        if: github.event_name == 'pull_request' && steps.filter.outputs.dev == 'true'
-        run: cd dev && terraform plan -no-color
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_GHA_NAMEOFREPO_NONPROD}}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_GHA_NAMEOFREPO_NONPROD }}
-        # GIT_SSH_COMMAND: "echo '${{ secrets.IHM_GH_SREBOT_SSH }}' > id_rsa
+      - name: Terraform Plan
+        id: plan
+        run: terraform plan -no-color
+        # GIT_SSH_COMMAND: "echo '${{ secrets.GH_SSH }}' > id_rsa
         # && ssh-keyscan github.com > known_hosts
         # && chmod 600 id_rsa known_hosts
         # && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
@@ -124,9 +88,26 @@ jobs:
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
+            const output = `#### Terraform Format and Style \`${{ steps.fmt.outcome }}\`
+            #### Terraform Initialization \`${{ steps.init.outcome }}\`
+            #### Terraform Validation \`${{ steps.validate.outcome }}\`
+            #### Terraform Plan \`${{ steps.plan.outcome }}\`
+            <details><summary>Show Plan</summary>
+            \`\`\`\n
+            ${process.env.PLAN}
+            \`\`\`
+            </details>
+            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+            
             github.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               body: process.env.STDOUT
             })
+            
+      # Ensure that if the plan fails, the workflow fails
+      - name: Terraform Plan or Validate Status 
+        id: tfps
+        if: steps.plan.outcome == 'failure' || steps.validate.outcome == 'failure'
+        run: exit 1
